version: '3'
services:
  web:
    build: './WebApp'
    ports:
      - "3000:3000"

  orders:
    build: './Orders'
    ports:
      - "3001:7777"
   
  books:
    build: './Books'
    ports:
      - "3002:4545"

  customers:
    build: './Customers'
    ports:
      - "3003:5555"

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./WebApp/views:/srv/www/static
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
      - books
      - orders
      - customers
